workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      xcode: latest
      cocoapods: default
      flutter: 3.24.4
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build for iOS Simulator
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' -sdk iphonesimulator
    artifacts:
      - build/ios/Debug-iphonesimulator/Runner.app
