workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: 3.24.4 # Specify the Flutter version you are using
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build for iOS Simulator
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' -sdk iphonesimulator
    artifacts:
      - build/ios/Debug-iphonesimulator/Runner.app
