# Integration section is required to make use of the keys stored in 

# Codemagic UI under Apple Developer Portal integration.

workflows:

  ios-workflow:

    name: iOS Workflow

    integrations:

      app_store_connect: Y4WUZ24HLK



    environment:

      # ...  



    scripts:

      # ...  



    publishing:

      app_store_connect:

        # Use referenced App Store Connect API key to authenticate binary upload

        auth: integration 



        # Configuration related to TestFlight (optional)



        # Optional boolean, defaults to false. Whether or not to submit the uploaded

        # build to TestFlight beta review.

        # Note: This action is performed during post-processing.

        submit_to_testflight: true



        # Optional boolean, defaults to false. Set to true to automatically expire 

        # previous build in review or waiting for review in Testflight before

        # submitting a new build to beta review. Expired builds will no longer be available for testers.

        # Note: This action is performed during post-processing.

        expire_build_submitted_for_review: true



        # Specify the names of beta tester groups that will get access to the build.

        beta_groups: 
          - Nexus

        









        



